---
- name: Install Docker on EC2
  hosts: devops-server
  become: true

  tasks:
    - name: Update packages
      yum:
        name: "*"
        state: latest
    
    - name: Install Docker Python SDK
      pip:
        name: docker

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Pull nginx image
      command: docker pull nginx

    - name: Run nginx container
      command: docker run -d -p 5000:80 --name devops-demo nginx
      ignore_errors: yes